name: Build Amelia Resurrection APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Setup Python for Chaquopy
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.0
    
    - name: Create config.json
      run: |
        mkdir -p app/src/main/assets
        echo '{
          "copilot_api_key": "${{ secrets.COPILOT_API_KEY }}",
          "copilot_endpoint": "https://api.githubcopilot.com/v1/chat",
          "elevenlabs_api_key": "${{ secrets.ELEVENLABS_API_KEY }}",
          "elevenlabs_voice_id": "${{ secrets.ELEVENLABS_VOICE_ID }}"
        }' > app/src/main/assets/config.json
    
    - name: Build Release APK
      run: gradle assembleRelease
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: amelia-resurrection-apk
        path: app/build/outputs/apk/release/*.apk
