name: Build Amelia Resurrection APK (With Fallback)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_HOME: /usr/local/lib/android/sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # ✅ Always install Android SDK + build-tools + NDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          build-tools: 33.0.2
          ndk: 21.4.7075529

      # ✅ Tell Gradle where the SDK is
      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          cat local.properties

      # ✅ Make Gradle wrapper executable if present
      - name: Make Gradle wrapper executable (if exists)
        run: |
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew
          fi

      - name: Set up Python for Chaquopy
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Create config.json
        run: |
          mkdir -p app/src/main/assets
          cat << EOF > app/src/main/assets/config.json
          {
            "mistrel_api_key": "${{ secrets.MISTREL_API_KEY }}",
            "mistrel_endpoint": "https://api.githubmistrel.com/v1/chat",
            "elevenlabs_api_key": "${{ secrets.ELEVENLABS_API_KEY }}",
            "elevenlabs_voice_id": "${{ secrets.ELEVENLABS_VOICE_ID }}"
          }
          EOF

      # 🔍 Debug: list Gradle tasks if wrapper is present
      - name: List Gradle tasks (if wrapper exists)
        run: |
          if [ -f ./gradlew ]; then
            ./gradlew tasks --all || true
          fi

      # 🚨 Fallback: Install Gradle if wrapper is missing or broken
      - name: Install Gradle (Fallback)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.0.1

      # 🛠 Build command with fallback
      - name: Build Release APK (Wrapper or Fallback)
        run: |
          if [ -f ./gradlew ]; then
            ./gradlew clean
            ./gradlew :app:assembleRelease --no-daemon --stacktrace
          else
            gradle clean
            gradle :app:assembleRelease --no-daemon --stacktrace
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: amelia-resurrection-apk
          path: app/build/outputs/apk/release/*.apk
